pipeline:
  name: osx
  identifier: osx
  projectIdentifier: CI_Sanity
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eoin
        repoName: osx-demo
        build: <+input>
  stages:
    - stage:
        name: Run
        identifier: Run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: fastlane setup
                  identifier: fastlane_setp
                  spec:
                    shell: Sh
                    command: |-
                      export LC_ALL=en_US.UTF-8
                      export LANG=en_US.UTF-8
                      export FASTLANE_USER=eoin_mcafee@hotmail.co.uk
                      export FASTLANE_PASSWORD=<+secrets.getValue('fastlanepassword')>
                      export BUILD_CERTIFICATE_BASE64=<+secrets.getValue('BUILD_CERTIFICATE_BASE64')>
                      export P12_PASSWORD=<+secrets.getValue('certpassword')>
                      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=<+secrets.getValue('fastlaneapppassword')>
                      sudo xcode-select -switch /Applications/Xcode_14.1.0.app
                      cd hello-harness

                      echo $BUILD_CERTIFICATE_BASE64 | base64 —decode > certificate.p12
                      security create-keychain -p P12_PASSWORD build.keychain
                      security default-keychain -s build.keychain
                      security unlock-keychain -p P12_PASSWORD build.keychain
                      security import certificate.p12 -k build.keychain -P $BUILD_CERTIFICATE_BASE64 -T /usr/bin/codesign
                      security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k P12_PASSWORD build.keychain
                      export IDENTITY_ID=security find-identity -v
                      /usr/bin/codesign --force -s IDENTITY_ID . -v

                      fastlane sigh
                      fastlane beta
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
