pipeline:
  name: osx
  identifier: osx
  projectIdentifier: CI_Sanity
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eoin
        repoName: osx-demo
        build: <+input>
  stages:
    - stage:
        name: Run
        identifier: Run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: fastlane setup
                  identifier: fastlane_setp
                  spec:
                    shell: Sh
                    command: |-
                      export LC_ALL=en_US.UTF-8
                      export LANG=en_US.UTF-8
                      export FASTLANE_USER=eoin_mcafee@hotmail.co.uk
                      export FASTLANE_PASSWORD=<+secrets.getValue('fastlanepassword')>
                      export BUILD_CERTIFICATE_BASE64=<+secrets.getValue('BUILD_CERTIFICATE_BASE64')>
                      export P12_PASSWORD=password
                      export KEYCHAIN_PASSWORD=admin
                      export BUILD_PROVISION_PROFILE_BASE64=<+secrets.getValue('BUILD_PROVISION_PROFILE_BASE64')>
                      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=<+secrets.getValue('fastlaneapppassword')>
                      sudo xcode-select -switch /Applications/Xcode_14.1.0.app
                      cd hello-harness

                      CERTIFICATE_PATH=/tmp/build_certificate.p12
                      PP_PATH=/tmp/build_pp.mobileprovision
                      KEYCHAIN_PATH=/tmp/app-signing.keychain-db

                      echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
                      echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH



                      fastlane sigh
                      fastlane beta
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
