kind: pipeline
type: vm
name: default

node:
  cluster: mac1

pool:
  use: osx-anka

steps:
- name: run
  commands:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - fastlane ios screenshots
