kind: pipeline
type: vm
name: default

pool:
  use: anka-arm64

steps:
- name: run
  commands:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - sudo xcode-select -switch /Applications/Xcode_14.1.0.app
  - fastlane build_mac_app --skip_codesigning

