kind: pipeline
type: vm
name: default

pool:
  use: anka-arm64

steps:
- name: run
  commands:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - xcode_select "/Applications/Xcode_14.0.1.app"
  - fastlane build_mac_app
