require 'fastlane/actions/app_store_connect_api_key'
require 'base64'

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_id = ENV["APP_ID"]

    # Decode the base64 encoded content of the .p8 file
    key_content = Base64.decode64(ENV["APP_STORE_CONNECT_KEY_BASE64"].delete("\x00"))

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: key_content
    )

    previous_build_number = latest_testflight_build_number(
      app_identifier: app_id,
      api_key: api_key,
    )

    current_build_number = previous_build_number + 1

    increment_build_number(
      xcodeproj: "hello-harness.xcodeproj",
      build_number: current_build_number
    )

    build_app(scheme: "hello-harness")
    upload_to_testflight(api_key: api_key)
  end
end
